# FROM nginx:alpine

# # Copy the Angular build output to the NGINX HTML directory
# COPY dist/book-frontend /usr/share/nginx/html

# # Expose port 80 for HTTP
# EXPOSE 80

# # Start NGINX in the foreground
# CMD ["nginx", "-g", "daemon off;"]
